name: iitchs_base
channels:
  - anaconda
  - conda-forge
  - defaults
  - gurobi
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - ampl-mp
  - ca-certificates
  - certifi
  - cppad
  - gmp
  - gurobi==11.0.3
  - ipopt
  - ld_impl_linux-64
  - libblas
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - liblapack
  - libopenblas
  - libstdcxx-ng
  - metis
  - mumps-include
  - mumps-seq
  - ncurses
  - openssl
  - pip
  - pyscipopt
  - python=3.8.11
  - python_abi=3.8
  - readline
  - scip
  - scotch
  - setuptools=52.0.0
  - sqlite
  - tbb
  - tk=8.6.10
  - wheel=0.36.2
  - xz
  - zlib
  - pip:
    - amply==0.1.4
    - antlr4-python3-runtime==4.8
    - cycler==0.10.0
    - decorator==5.0.9
    - docutils==0.16
    - sphinx
    - sphinx-rtd-theme
    - myst-parser
    # - gurobipy==11.0.3
    - kiwisolver==1.3.1
    - matplotlib>=3.4.3
    - multimethods==1.0.0
    - networkx==3.0
    - numpy
    - pandas==2.0.3
    # - git+ssh://git@github.mit.edu/iitchs/pp3#egg=pp
    - pulp==2.4
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pyyaml
    - scipy
    - shapely==1.7.1
    - simplekml==1.3.5
    - six
    - z3-solver==4.8.8.0
    - git+ssh://git@github.com/uqfoundation/pathos@cf3d8dd0ad10ca267ccd5355f3fb24d48b6ed6ab
    - pytest
